sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

branches:
  only:
    - master
    - stable
    - ili2pg-v4

install: true

script:
  - ./gradlew --no-daemon clean gretl:classes
  - ./gradlew --no-daemon gretl:test gretl:dbTest
  - ./gradlew clean gretl:s3Test -Ds3AccessKey=$S3_ACCESS_KEY -Ds3SecretKey=$S3_SECRET_KEY -Ds3BucketName=ch.so.agi.gretl.test
  - ./gradlew gretl:build gretl:publishPluginMavenPublicationToMavenLocal -x test
  - cd runtimeImage/
  - ./build-gretl.sh $TRAVIS_COMMIT $TRAVIS_BUILD_NUMBER
  - cd ..
  - ./gradlew --no-daemon gretl:jarTest
  - ./gradlew --no-daemon gretl:jarS3Test -Ds3AccessKey=$S3_ACCESS_KEY -Ds3SecretKey=$S3_SECRET_KEY -Ds3BucketName=ch.so.agi.gretl.test
  - ./gradlew --no-daemon gretl:imageTest
  - ./gradlew --no-daemon gretl:imageS3Test -Ds3AccessKey=$S3_ACCESS_KEY -Ds3SecretKey=$S3_SECRET_KEY -Ds3BucketName=ch.so.agi.gretl.test

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew --no-daemon gretl:publishPlugins
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: runtimeImage/push-gretl.sh $dockerhub_pwd
    on:
      branch: master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
