sudo: required

language: java

services:
  - docker

branches:
  only:
    - master
    - stable

install: true

jobs:  
  include:
    - stage: "Compile"               
      script: ./gradlew --no-daemon clean classes
    - stage: "Tests"
      name: "Unit Tests"
      script: ./gradlew --no-daemon clean gretl:test gretl:dbTest
