sudo: required

language: java

services:
  - docker

branches:
  only:
    - master
    - stable

install: true

script:
  - ./gradlew --no-daemon clean gretl:classes
  - ./gradlew --no-daemon gretl:test gretl:dbTest
  - ./gradlew gretl:build gretl:publishPluginMavenPublicationToMavenLocal -x test
  - cd runtimeImage/
  - ./build-gretl.sh $TRAVIS_COMMIT $TRAVIS_BUILD_NUMBER
  - cd ..
  - ./gradlew --no-daemon gretl:jarTest
  - ./gradlew --no-daemon gretl:imageTest

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew --no-daemon gretl:publishPlugins
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: runtimeImage/push-gretl.sh $dockerhub_pwd
    on:
      branch: master
