name: gretl

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew clean gretl:classes 
      - name: Unit Tests 
        run: |
          ./gradlew gretl:build gretl:publishPluginMavenPublicationToMavenLocal -x test
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      - name: Build Docker Image
        run: |
          cd runtimeImage/
          echo foo
          echo $TRAVIS_BUILD_NUMBER
          echo bar
          ./build-gretl.sh $TRAVIS_COMMIT $TRAVIS_BUILD_NUMBER
          cd ..
        env:
          TRAVIS_COMMIT: ${{ env.GITHUB_SHA }}
          TRAVIS_BUILD_NUMBER: ${{ github.run_number }}
      - name: List Docker Images
        run: docker images
      - name: Publish Docker image
        run: ./runtimeImage/push-gretl.sh $DOCKERHUB_PWD
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}