name: gretl

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew clean gretl:classes 
      - name: Unit Tests 
        run: |
          ./gradlew gretl:test gretl:dbTest
          ./gradlew clean gretl:s3Test -Ds3AccessKey=$S3_ACCESS_KEY -Ds3SecretKey=$S3_SECRET_KEY -Ds3BucketName=ch.so.agi.gretl.test
      - name: Integration Test (Jar)
        run: |
          ./gradlew gretl:jarTest
          ./gradlew gretl:jarS3Test -Ds3AccessKey=$S3_ACCESS_KEY -Ds3SecretKey=$S3_SECRET_KEY -Ds3BucketName=ch.so.agi.gretl.test
        env:
          BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}

      # - name: Push docker image
      #   run: |
      #     export CI_JOB_TIMESTAMP=$(date +%Y%m%dT%H%M%S)
      #     echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      #     docker images
      #     ./gradlew pushDockerImages
      #   env:
      #     DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      #     DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      #     DOCKER_ACCOUNT: sogis
      #     DOCKER_REPO: cadastre-web-service
      